platform :ios, '12.0'

target 'iOS' do
  use_frameworks!
  pod 'SnapKit', '~> 4.2.0'
  pod 'Alamofire', '~> 4.7.3'
  pod 'Kingfisher', '~> 4.10.1'
  pod 'SwiftLint', '~> 0.28.1'
  pod 'R.swift', '~> 5.0.0.alpha.2'
  pod 'IQKeyboardManagerSwift', '~> 6.2.0'

  target 'iOSTests' do
    inherit! :search_paths
  end

end
